### ISSUE TITLE
多线程编程相关知识

### ISSUE THREAD

**Issue by pingqiangguo** [DrAugus/draugus.github.io#151]
1. 一般在实际开发中, 都会使用哪些锁? 请就实际开发角度举例, 在什么样的情况下使用适合使用什么类型的锁.
2. 在c++标准中提供了 std::thread, std::async,  std::package_task, std::promise等模块以支持异步开发, 在实际开发中一般使用那种呢, 还是直接使用pthread?
3. 在多线程开发中, 有没有什么好的编程模式或程序设计方法, 能够尽可能的避免锁带来的性能消耗和死锁问题?

**Comment by DrAugus** [comment]
commit: 0d3d2859b5edfd08d88f230e2369359edc5cecb8

**Comment by DrAugus** [comment]
commit: 0d3d2859b5edfd08d88f230e2369359edc5cecb8

**Comment by DrAugus** [comment]
commit:  0d3d2859b5edfd08d88f230e2369359edc5cecb8   
[online][link]


[link]: https://nuxt-docus-draugus.vercel.app/interview/cpp/4-easy-tips-on-using-threads-and-mutexes-in-cpp

**Comment by DrAugus** [comment]
6948c5531fc837f931d975bda5c7895f78cf570e
