### ISSUE TITLE
libasan 代码演示

### ISSUE THREAD

**Issue by pingqiangguo** [DrAugus/draugus.github.io#152]
对于你关于采用libasan进行c++内存泄漏方面的介绍非常好, 不过在该文档中, 你只给了相关的命令和参数, 这对于新手可能不是很友好(说的就是我), 你能不能对它专门写一个实例演示呢. 🙏🙏请附上演示代码, 使用命令和执行结果🙏🙏.

**Comment by DrAugus** [comment]
You will see it [here][online] later. [source][link]


[online]: https://nuxt-docus-draugus.vercel.app/code/cpp/asan#sample
[link]: https://github.com/DrAugus/draugus.github.io/blob/master/nuxt-docus/content/1.code/cpp/asan.md#sample

**Comment by DrAugus** [comment]
6948c5531fc837f931d975bda5c7895f78cf570e
